### ISSUE TITLE
旋转目标检测部署

### ISSUE THREAD

**Issue by Pytrick520** [DeployAI/nndeploy#14]
您好，请问下可以支持下旋转目标检测的C++部署吗？例如这个[yolov8](https://blog.csdn.net/qq_39128381/article/details/131962684#comments_28809565)的

**Comment by Alwaysssssss** [comment]
能把算法链接发一下吗？对于旋转目标检测我们还不是那么熟悉，您能抽时间给我介绍一下吗

**Comment by Alwaysssssss** [comment]
欢迎添加我的微信以及进群和我们沟通呀
