### ISSUE TITLE
单个pipeline推理在多线程访问下是否安全

### ISSUE THREAD

**Issue by ximitiejiang** [DeployAI/nndeploy#28]
请问下如果是多个线程同时访问单个pipeline，是否线程安全？如何避免线程冲突

**Comment by Alwaysssssss** [comment]
单个pipeline非线程安全呀。这里面有以下几个原因呀：（1）很多推理后端非线程安全（2）在pipeline里面做线程安全代价特别大

想要多线程使用单个pipeline，建议在上层加锁

**Comment by tp-nan** [comment]
如果节点是线程安全的，那么pipeline就是线程安全的。建议在node内部，推理后端上添加一层线程安全层（实现batching，多实例）
